/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   fabric-imgix.js
 *   fabric-imgix.js
 */

/**
 * `fabric-imgix`
 */
declare class FabricImgix extends Polymer.Element {

  /**
   * Connected callback
   */
  connectedCallback(): void;

  /**
   * Ready event
   */
  ready(): void;

  /**
   * Smart size observer
   */
  _smartSize(): void;

  /**
   * Check network status
   */
  networkStatus(): void;
}

interface HTMLElementTagNameMap {
  "fabric-imgix": FabricImgix;
  "fabric-imgix": FabricImgix;
}

/**
 * `fabric-imgix`
 */
declare class FabricImgix extends Polymer.Element {

  /**
   * Connected callback
   */
  connectedCallback(): void;

  /**
   * Ready event
   */
  ready(): void;

  /**
   * Smart size observer
   */
  _smartSize(): void;

  /**
   * Check network status
   */
  networkStatus(): void;
}
